---
###################################################
# Playbook update APT packege because CVE-2019-3462
# #################################################
- name: Verify version
  command: dpkg-query -W --showformat='${version}' apt
  register: apt_check_version
  failed_when: apt_check_version.stdout > "{{ apt_version }}"
  changed_when: apt_check_version.stdout != "{{ apt_version }}"

- name: Verify Repository http://cdn-fastly.deb.debian.org/debian-security stable/updates main
  shell: grep -R "http://cdn-fastly.deb.debian.org/debian-security stable/updates main" /etc/apt/sources.list | wc -l
  register: apt_check_repository
  changed_when: apt_check_repository.stdout = 0

- name: ADD Repository deb http://cdn-fastly.deb.debian.org/debian-security stable/updates main
  command: echo "deb http://cdn-fastly.deb.debian.org/debian-security stable/updates main" >> /etc/apt/sources.list
  when: apt_check_version.changed and apt_check_repository.changed

- name: Update and Upgrade APT
  apt: 
    update_cache: yes
    autoremove: yes
  when: apt_check_version.changed

- name:  Install the APT packege to a latest version.   
  command: apt-get install apt apt-utils apt-transport-https -y
  when: apt_check_version.changed