---
###################################################
# Playbook update APT packege because CVE-2019-3462
# #################################################
- name: Verify version
  command: dpkg-query -W --showformat='${version}' apt
  register: apt_check_version
  failed_when: apt_check_version.rc > "{{ apt_version }}"
  changed_when: apt_check_version.stdout != "{{ apt_version }}"

- name: ADD Repository deb http://cdn-fastly.deb.debian.org/debian-security stable/updates main
  command: add-apt-repository "deb http://cdn-fastly.deb.debian.org/debian-security stable/updates main"
  when: apt_check_version.changed
  
- name: Update and Upgrade APT
  apt: 
    update_cache: yes
    autoremove: yes
  when: apt_check_version.changed

- name:  Install the APT packege to a latest version.   
  command: apt-get install apt -y
  when: apt_check_version.changed